### ISSUE TITLE
Create an official release

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/tracey-rabbitmq-neo4j-bridge#5]
We will try to create an official release. Preferably with some kind of CI setup in Travis

**Comment by buep** [comment]
Easy, just copy the same steps as we did for our two other projects in Tracey that releases to github releases page :-)

**Comment by buep** [comment]
Let me know if you need help. It will be good to install the travis cli as this have command to do it. See the release sections in the cli generator project.

**Comment by MadsNielsen** [comment]
Right i finally got it done. :) I thought it was enough to just do the `travis setup releases`. That's enough to create the template for the release. 

What was missing, and it took me a while to realize it is that you also have to enable the travis service for the repository. 

That is done with the `travis login` and `travis enable` commands. But we've got a downloadable binary for use now. So that's good. 

I'll create a description of this proces which i've created issue #6 for.
